### ISSUE TITLE
new vers 1.4.12.25 is a VIRUS...??

### ISSUE THREAD

**Issue by p060477** [sebdelsol/sfvip-all#10]
here it is the virustotal report...:
https://www.virustotal.com/gui/file/6cfba998d314e3d5226692d3b479c33135cbae35df10c6257a6329d755c92795

**23 security vendors and no sandboxes flagged this file as malicious**

**Comment by sebdelsol** [comment]
Duplicate #8

**Comment by p060477** [comment]
**23 security vendors and no sandboxes flagged this file as malicious**
why the olders vers. has really not this very bad score...??...:(

**Comment by sebdelsol** [comment]
Please check the issues before posting

**Comment by p060477** [comment]
Please check VIRUSTOTAL before releasing new vers. of yr tool....:
**23 security vendors and no sandboxes flagged this file as malicious**
_why the olders vers. has really not this very bad score...??...:(_

**Comment by sebdelsol** [comment]
Please read the issues before posting.
I use _Pyinstaller_ instead of _Nuitka_ which gives more false positives based on the exact same build (check #8).

Your link show a scan on a file with the wrong md5. 
The actual hash of the 1.4.12.25 installer is `cb9a3c0a3e6f31ad3d22acd5bae3a4f8`: you can check [**here**](https://github.com/sebdelsol/sfvip-all/blob/master/build/update_x64.json). 
So it seems you either checked the wrong installer or your installer has been tampered with.

**Comment by p060477** [comment]
i have -portabilized- yr installer cause i really do want to use as much portable sw as i can,hope you understand,
so maybe this is the reason of the different md5...and i really do suggest you to offer also a portable way of yr tool....
and i re-suggest you to compile yr tools ,as in the past, in order not to have that so really bad virsutotal score...
sanyway the worst thing is that ALSO my av malwarebytes really do not ALLOW me to use yr tool in the new 1.4.12.25....so this is why i'm trying to make you thinking deeply and carefully about this....
up to now i'm friendly use yr 1.4.12.20...and in my -portable- way....
it is really all up to you if you want yr potentially users be confident in using yr tool
best regards

**Comment by p060477** [comment]
maybe you really do not read well what i've written..i pray you to do and understand....:
i have -portabilized- yr installer cause i really do want to use as much portable sw as i can,hope you understand,
so maybe this is the reason of the different md5...and i really do suggest you to offer also a portable way of yr tool....
and i re-suggest you to compile yr tools ,as in the past, in order not to have that so really bad virsutotal score...
anyway the worst thing is that ALSO my a/v malwarebytes really do not ALLOW me to use yr tool in the new 1.4.12.25....so this is why i'm trying to make you thinking deeply and carefully about this....
up to now i'm friendly use yr 1.4.12.20...and in my -portable- way....
it is really all up to you if you want yr potentially users be confident in using yr tool
best regards

**anyway the worst thing is that ALSO my a/v malwarebytes really do not ALLOW me to use yr tool in the new 1.4.12.25....so this is why i'm trying to make you thinking deeply and carefully about this....
up to now i'm friendly use yr 1.4.12.20...and in my -portable- way....**

**Comment by p060477** [comment]
instead of loosin yr time deleting comment you do not like should be really better **you release a new ver. that malwarebytes and a/v serious do not block as malware**
it is a very friendly suggestion
it is up to you feelin free to follow
**best regards**

**Comment by sebdelsol** [comment]
I've deleted your two last comments because you keep being quite unpleasant. 
I have already explained why what's you're suggesting [doesn't resolve the residual AV false positives issue](https://github.com/sebdelsol/sfvip-all/issues/8#issuecomment-1914586960).

If you'd rather have a _Nuitka_ build version because you think it will be better for you, you have everything in this repo to build one. Feel free to raise an issue if you need help or have questions.

**Comment by p060477** [comment]
thxs and apologize me 
but i really only want to use yr tool without stopping my malwarebytes or put yr tool in its white list
i repeat that i'm still using yr not so old vers 1.4.12.20 **without any issue**...
so i simply pray you to release a new vers according to it
but to be clear: i really do not want to be unpleasant or upsettin or ugly or so on
i reperat my is only a simply  **suggestion**
anyway the only thing i'd like to say to you is, whatever you will do or not :
THANKS FOR YR EFFORTS AND PRECIOUS TIME YOU GIFTED TO US

**Comment by sebdelsol** [comment]
v**1.4.12.26** is build with the new _Nuitka_ 2.0 which has (at the moment) very [few false positives](https://www.virustotal.com/gui/file/6709a41cec427d5906d526812a9fb0d4d41390c0fd7e5a11e03b451b583144c3).

**Comment by p060477** [comment]
hi, first let me thank you again for all you are done for us
i confirm that the latest 1.4.12.26 as really no issue with my malwarebytes a/v
i am able so to use it confidently
so now i'm just using yr very latest 1.4.12.26
i re-underline and re-write:
THANKS FOR YR EFFORTS AND PRECIOUS TIME YOU GIFTED TO US
cheers

**Comment by sebdelsol** [comment]
So you know: I've actually built a solution without any false positives. 
It just means you have to resolve all Python dependencies on your own.
It's doable but a nightmare to maintain: that's why I use either _Nuitka_ or _Pyinstaller_...
The main drawback is that AVs tend to flag those a malware since both are heavily used by malware creators...

**Comment by p060477** [comment]
thxs so much indeed again
now i am able so to use it confidently
now i'm just using yr very latest 1.4.12.26 and all seems very fine
i re-underline and re-write:
THANKS FOR YR EFFORTS AND PRECIOUS TIME YOU GIFTED TO US
cheers

**Comment by sebdelsol** [comment]
|_2 build solutions_ | _Nuitka≥2.0_  | _Pyinistaller≥6.3_|
| -: | :-: | :-: |
| **Distribution size** | Bigger  | Smaller |
| **Run time memory** | Bigger  | Smaller |
| **Run time speed** | Faster | Slower |
| **Build tool chain** |Harder| Easier|
| **AV false positives** | Low | High |

**Comment by p060477** [comment]
in my personal case the only things is to be able to use it without stopping malwarebytes or adding the .exe to its whitelist
but in any case:
i re-underline and re-write:
THANKS FOR YR EFFORTS AND PRECIOUS TIME YOU GIFTED TO US
cheers
