### ISSUE TITLE
is it possible to play a movie in mpd format ?

### ISSUE THREAD

**Issue by nyihan** [sebdelsol/sfvip-all#13]
please add to open mpd desh file format.

**Comment by sebdelsol** [comment]
_Sfvip Player_ already plays `.mpd` files since it's build upon [_mpv_](https://mpv.io/).
But you're right _Sfvip Player_ doesn't handle _mpd_ accounts.

Please bear in mind _Sfvip All_ only wraps the existing _Sfvip Player_ to add features. 
But there are limits to what _Sfvip All_ can do because _Sfvip Player_ is not open source.

If you need this extra features, please raise an issue in  [_Sfvip Player_ github repo](https://github.com/K4L4Uz/SFVIP-Player/tree/master)
