### ISSUE TITLE
Failing to import from epgshare01

### ISSUE THREAD

**Issue by max1c** [sebdelsol/sfvip-all#2]
I'm not sure if it's because it's too large but the [epg_ripper_ALL_SOURCES1.xml.gz](https://epgshare01.online/epgshare01/epg_ripper_ALL_SOURCES1.xml.gz) from https://epgshare01.online/epgshare01/ is failing to import. The others ones seem to work well.

EDIT: Also, is there a portable version?

**Comment by sebdelsol** [comment]
Yeah the xml is too huge and causes memory issues. So I'll have to find a way to serialize it on the fly. I'm on it. Expect a new version in the following days.

There's no portable version anymore : I've switched from Nuitka single file to Nsis because it gives way less AV false positive. And maintaining a portable version became a PITA. So I ditched it.

**Comment by sebdelsol** [comment]
It's fixed in v1.4.12.4:
I now use `lxml.etree.iterparse`  that processes the tree on the fly and prevents the memory issue.
The whole **epg** is processed into a **dictionary**: it takes 1GB instead of 10GB when it was an **xml tree**.
The **epg** is longer to process though : it takes 30s to 1mn for this one. So its progress is shown in the UI and can be interrupted.

**Comment by max1c** [comment]
Hey, thanks so much for a quick turn around. I appreciate it. I also understand the complications with portable version. Cheers!
